"$schema" = "https://starship.rs/config-schema.json"

add_newline = false

format = """
$directory$git_branch$git_status$aws$terraform
[ÓπÅ  ]($style)"""

[aws]
format = '[$symbol($profile)(\($region\))(\[$duration\])]($style) '
symbol = ''

[aws.region_aliases]
ap-northeast-1 = 'tokyo'

[git_branch]
symbol = ""
format = "[$symbol$branch]($style) "

[directory]
truncation_length = 3
truncation_symbol = ""
format = "[$path]($style) "

